version: '3.3'
services:
  backend:
    build: ./simple-api/simple-api
    networks:
      - my-network
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://devopstp01_database_1:5432/db

  database:
    build: ./Database
    networks:
      - my-network

  httpd:
    build: ./HTTP_Server
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
